### ISSUE TITLE
spdlog leaks into librmm (?)

### ISSUE THREAD

**Issue by leofang** [conda-forge/librmm-feedstock#2]
Not sure if this is intended --- I downloaded the `librmm` package and inspected the files locally, and this is what I saw:
<img width="607" alt="截圖 2021-04-28 下午12 06 24" src="https://user-images.githubusercontent.com/5534781/116436209-2a772700-a81a-11eb-9975-1da1b4ef5327.png">
There are headers and also a static library for spdlog, but should these be included in the `librmm` package? I thought `spdlog` is a standalone package?
https://github.com/conda-forge/librmm-feedstock/blob/32b6251bf7baaaa908701b3ff6ac54eba070461e/recipe/meta.yaml#L27
My guess is these are due to `spdlog` being fetched by cmake instead of conda.

cc: @kkraus14 @jakirkham @rlratzel

**Comment by kkraus14** [comment]
Yep, need it in the host section instead of just the run section

**Comment by isuruf** [comment]
`lib64` needs to be changed to `lib`

**Comment by leofang** [comment]
> Yep, need it in the host section instead of just the run section

It has `run_exports` so I think we just need the host section 
https://github.com/conda-forge/spdlog-feedstock/blob/c96430f1cb8e576908e2cd295e9bf73a4a245d57/recipe/meta.yaml#L15-L16

**Comment by leofang** [comment]
@kkraus14 What exactly does the build script do? Why isn't it generating a `librmm.so` shared library?

**Comment by leofang** [comment]
(I mean I know it's a header-only library, so an equivalent question is why do we need a cmake build script for rmm? We didn't need one for Thrust/CUB.)

**Comment by kkraus14** [comment]
I don't quite remember if the CMake install process generates the correct CMake pieces to allow someone to do a `find_package(RMM)`

**Comment by leofang** [comment]
OK. There are `rmm-*.cmake` included in the package, so I think this is why.

**Comment by jakirkham** [comment]
Think we need it in both host and run since it is also needed by libraries including RMM

**Comment by leofang** [comment]
Yes, @jakirkham, I just pushed #3.

**Comment by jakirkham** [comment]
Thanks Leo! 😄

Proposing we mark the old packages broken in PR ( https://github.com/conda-forge/admin-requests/pull/259 ). So that users don't get these by accident
