### ISSUE TITLE
Thrust/CUB should be run-exported

### ISSUE THREAD

**Issue by leofang** [conda-forge/librmm-feedstock#30]
This affects RMM because the Cython layer also needs to include Thrust (and therefore CUB too) headers. It's better that librmm exports it to ensure the same version is seen when building RMM.

**Comment by leofang** [comment]
This need is revealed after @kkraus14's recent fix in Thrust/CUB's cmake support (https://github.com/conda-forge/thrust-feedstock/pull/15, https://github.com/conda-forge/cub-feedstock/pull/17).

**Comment by leofang** [comment]
Findings learned from #31 and https://github.com/conda-forge/rmm-feedstock/pull/11:
- In `librmm` to set to an external Thrust, we need to use `-DCPM_Thrust_SOURCE`. But in `rmm`, we need to use `-DThrust_ROOT`.
- However, we currently do not apply the CPM trick to `librmm` because it doesn't seem to be the most elegant solution to the include path issue (https://github.com/conda-forge/librmm-feedstock/pull/31#issuecomment-1138988403)
- As a result, and `librmm` downstream, including `rmm` better use the Thrust bundled in `librmm` to not be stripped by the version mismatch error.

**Comment by kkraus14** [comment]
I don't think this is an issue in practice anymore. The package ships thrust and cub in a `rapids` subdirectory so they exist as needed. I believe it is done this way since other RAPIDS packages have had the need to patch thrust and cub.

**Comment by jakirkham** [comment]
That sounds right to me. Thanks Keith! 🙏
